version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: almaeng-postgres-local
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./local-db-data:/var/lib/postgresql/data
    networks:
      - almaeng-network

  redis:
    image: redis:alpine
    container_name: almaeng-redis-local
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./local-redis-data:/data
    networks:
      - almaeng-network

networks:
  almaeng-network:
    driver: bridge
